export const SEND_MESSAGE = 'CHAT/SEND_MESSAGE';
export const SET_MESSAGE = 'CHAT/SET_MESSAGE';
export const LOAD_MESSAGES_START = 'CHAT/LOAD_MESSAGES_START';
export const LOAD_MESSAGES_FINISH = 'CHAT/LOAD_MESSAGES_FINISH';
