export const SEND_TEXT_MESSAGE = 'CHAT/SEND_TEXT_MESSAGE';
export const SET_MESSAGE = 'CHAT/SET_MESSAGE';
export const RECEIVE_MESSAGES = 'CHAT/RECEIVE_MESSAGES';
export const RECEIVE_MESSAGE = 'CHAT/RECEIVE_MESSAGE';
export const LOAD_MESSAGES_START = 'CHAT/LOAD_MESSAGES_START';
export const LOAD_MESSAGES_FINISH = 'CHAT/LOAD_MESSAGES_FINISH';
