export const FIND_USERS = 'SEARCH/FIND_USERS';
export const SET_USERS = 'SEARCH/SET_USERS';
export const UNSET_USERS = 'SEARCH/UNSET_USERS';
export const SEARCH_START = 'SEARCH/SEARCH_START';
export const SET_SEARCH_RESULT = 'SEARCH/SET_SEARCH_RESULT'
