export const FIND_USERS = 'SEARCH/FIND_USERS';
export const SET_USERS = 'SEARCH/SET_USERS';
export const UNSET_USERS = 'SEARCH/UNSET_USERS';
export const SEARCH_START = 'SEARCH/SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH/SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH/SEARCH_FAILURE';
export const SEARCH_FINISH = 'SEARCH/SEARCH_FINISH';
