export const FETCH_USER = 'USER/FETCH_USER';
export const SET_USER = 'USER/SET_USER';
export const CREATE_USER = 'USER/CREATE_USER';
export const ENTER_CHANNEL = 'USER/ENTER_CHANNEL';
export const SET_CHANNELS = 'USER/SET_CHANNELS';
export const SET_CURRENT_CHANNEL = 'USER/SET_CURRENT_CHANNEL';
