export const FETCH_USER = 'USER/FETCH_USER';
export const SET_USER = 'USER/SET_USER';
export const CREATE_USER = 'USER/CREATE_USER';
export const CONNECTION_CHECKING_SUCCESS = 'USER/CONNECTION_CHECKING_SUCCESS';
export const CONNECTION_CHECKING_FAILURE = 'USER/CONNECTION_CHECKING_FAILURE';
export const CONNECTION_CHECKING_START = 'USER/CONNECTION_CHECKING_START';
export const CONNECTION_CHECKING_FINISH = 'USER/CONNECTION_CHECKING_FINISH';
